name: flutter_build

# This workflow will trigger on push or pull request events to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This job builds the web version of the Flutter app
  build_web:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Sets up Java JDK 11 on the runner
      - uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: '11'
      # Sets up Flutter SDK on the runner
      - uses: subosito/flutter-action@v4
        with:
         channel: 'stable'
      # Prints the Flutter version
      - run: flutter --version
      # Installs dependencies for the Flutter project
      - name: Install dependencies
        run: flutter pub get
      # Analyzes the project's Dart source code
      - name: Analyze project source
        run: dart analyze
      # Builds the web version of the Flutter app
      - name: Build web
        run: flutter build web

  # This job builds the Windows version of the Flutter app
  build_windows:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Sets up Flutter SDK on the runner
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      # Enables Flutter desktop support
      - run: flutter config --enable-windows-desktop
      # Builds the Windows version of the Flutter app
      - run: flutter build windows
  
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
              sudo apt-get install -y ninja-build libgtk-3-dev
              flutter config --enable-linux-desktop
              flutter build linux
